---
- name: Downlaod latest jar and start application
  hosts: localhost
  connection: local
  tasks:
  - name: stopping application application
    shell: "sh /packages/bin/stop-{{ APP_NAME }}.sh"
    args:
      executable: /bin/bash
    register: start
  - debug:
      var: start
      verbosity: 2
  - name: downloading jar
    get_url:
      force: yes
      url: "{{ ARTIFACT_URL }}"
      dest: "/packages/apps/{{ APP_NAME }}/{{ APP_NAME }}.jar"
      mode: 0755
  - name: starting application application
    shell: "sh /packages/bin/start-{{ APP_NAME }}.sh"
    args:
      executable: /bin/bash
    register: stop
  - debug:
      var: stop
      verbosity: 2