---
- name: Downlaod latest jar and start application
  hosts: localhost
  connection: local
  tasks:
  - name: downloading jar
    get_url:
      force: yes
      url: "{{ ARTIFACT_URL }}"
      dest: "/tmp/{{ APP_NAME }}.jar"
  - name: starting application
    command: "java -jar /tmp/{{ APP_NAME }}.jar"
