server:
    port: 9090
    servlet.context-path: /validator
logging:
  level.root: info
  level.io.exnihilo: debug
  file: /packages/logs/yaml-editor/yaml-editor.log
spring.pid.fail-on-write-error: true
spring.pid.file: /packages/config/yaml-editor/yaml-editor.pid