application:
  name: '@project.name@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'
spring:
  profiles.active: prod
  pid.fail-on-write-error: true
server:
  port: 8090
logging:
  level.root: info
  level.io.exnihilo: debug
management:
  endpoints:
    web.exposure.include: "*"
    web.exposure.exclude: loggers
  endpoint:
    shutdown.enabled: true
