application:
  name: '@project.name@'
  description: '@project.description@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'
swagger:
  contactName: 'Anand Varkey Philips'
  contactUrl: 'https://about.me/anandvarkeyphilips'
  contactEmail: 'anandvarkeyphilips@gmail.com'
  licenseUrl: 'https://github.com/anandvarkeyphilips/enterprise-validator/blob/master/LICENSE'
  termsOfServiceUrl: 'https://www.termsfeed.com/live/21586f44-4d39-4c46-bc36-c6e5f0063ba0'
spring:
  profiles.active: dev
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
