server:
  port: 9090
  servlet.context-path: /validator-microservice
logging:
  level.root: info
  level.io.exnihilo: debug
  file: /packages/logs/validator-microservice/validator-microservice.log
spring.pid.fail-on-write-error: true
spring.pid.file: /packages/config/validator-microservice/validator-microservice.pid

management:
  endpoints:
    web.exposure.include: "*"
    web.exposure.exclude: loggers
  endpoint:
    shutdown.enabled: true